version: '3.7'

volumes: 
    database: 
      
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
    php:
        image: bitnami/php-fpm:7.4.5
        volumes:
            - ./:/app
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: docker
        volumes:
            - 'database:/var/lib/mysql'
        